### ISSUE TITLE
Dedicated server crash on startup

### ISSUE THREAD

**Issue by vedrit** [Hedede/vintagestory-mods#1] opened 2024-04-27 23:27 UTC
I get a crash from this mod on my dedicated server when it starts up. Here's the log https://pastebin.com/4XJU65PJ
Server is running v1.19.7, mod v2.0.9

**Comment by Hedede** [comment] 2024-04-28 08:10
Unable to reproduce the issue. Do you have any other mods installed?
Judging by a log there's a conflict with a command added by another mod. I added a new version that might fix it, but I can't guarantee without knowing what causes the conflict.

**Comment by vedrit** [comment] 2024-04-28 10:16
I've got quite a few mods, but I only encountered this crash after updating Primitive Survival, Better Ruins, and VS Village
If there are any known incompatibilities, that would be good to know.

**Comment by Hedede** [comment] 2024-04-28 13:25
I couldn't find anything in these mods that would conflict with this mod. Since 2.0.10 fixes it I'm marking this as resolved.

**Closed by Hedede** 2024-04-28 13:25 UTC
Labels: bug, mod: cartographer
